0
Unconfigured
all
IP_Routed
1_ALL_NOVLAN
0
0
NULL
NULL
0
0
0
0
1
DHCP
NULL
NULL
NULL
1
0
NULL
1500
NULL
0
NULL
NULL
0
NULL
0
NULL
NULL
0
0
1
0
-1
0
0
NULL
NULL
1
Unconfigured
NULL
NULL
AutoConfigured
NULL
1
NULL
PrefixDelegation
NULL
0
0
NULL
NULL
0
0
1400
1
