default_username=avengers
default_password=avengers
voip_1_username=admin
voip_1_password=admin
voip_2_username=admin
voip_2_password=admin
option16_encry_enable=no
option16_valuemode=2
voip_username_passwd=admin,admin
option16_add_gatewayid=yes
Gateway_ID=abcdefghijklmnopqrstuvwx
option16_type=34
