#注释行是#号开始
#首行以[]中带模块名开始，第二行是否执行的开关(yes或no)，第三行是日志触发条件，第四行是日志运行时间，第五行是日志关闭条件，第六行是开关控制的日志文件个数，第七行开始每行是开关控制的各日志的路径
#每个模块配置，各行之间不能有空白行或注释行

[igmp]
run=no
echo debug 1 >/proc/tc3162/igmp_hwnat
10
echo debug 0 >/proc/tc3162/igmp_hwnat; dmesg -c > /var/mtkigmp_log
1
/var/mtkigmp_log


[dnsmasq]
run=yes
touch /var/dns_log_enable
15
rm /var/dns_log_enable
1
/var/dnsmasq_modelog
