
#wlan 过程
/var/meshapp_modelog
/var/meshinfo_modelog
/var/libmesh_modelog
/var/lib1905_modelog
/var/devfunc_modelog
/var/wifilib_modelog
/var/wifiitf_modelog
/var/wifictl_modelog
/var/wifi_drv_modelog
/var/libcpeapi_modelog
/var/onboarded_info
/var/meshapi_modelog

#wlan 配置
/ptconf/pt_wifi/wifictl_2g.cfg
/ptconf/pt_wifi/wifictl_5g.cfg
/ptconf/pt_wifi/wifictl_6g.cfg
/ptconf/factory_conf
/ptconf/usrconfig_conf
/data/.user_nvram.setting
/ptconf/pt_wifi/meshmode
/ptrom/bin/wifi.txt
/etc/Wireless/RT2860AP/RT2860AP.dat
/etc/Wireless/RT2860AP_AC/RT2860AP.dat
/etc/Wireless/RT2860AP/DBDC_card0.dat
/etc/ecnt_cfg.txt
/etc/map_cfg.txt
/etc/mapd_cfg.txt
/etc/mapd_strng.conf
/etc/wts_bss_info_config
/var/scanresults_0
/var/scanresults_1 

#组网信息（从路由）
/tmp/dump.txt
