max_leases	254	#must be first
start	0.0.0.0
end	255.255.255.0
interface	br0
lease_file	/var/udhcpd_lan.leases	#default: /var/lib/misc/udhcpd.leases
pidfile	/var/run/udhcpd_lan.pid	#default: /var/run/udhcpd.pid

option	dns	192.168.1.1
option	subnet	255.255.255.0
option	router	192.168.1.1
option	lease	604800

# Static leases map

HGW_start	192.168.2.0
HGW_end	192.168.2.20
STB_start	192.168.1.155
STB_end	192.168.1.166
Camera_start	192.168.1.133
Camera_end	192.168.1.144
Computer_start	192.168.1.111
Computer_end	192.168.1.122
Phone_start	192.168.1.177
Phone_end	192.168.1.188

#IP  munber limit
IP_Number 4
IP_limit_enable=yes
dns_relay_enable=1
enable125=yes
