LowRSSIAPSteerEdge_RE=20
LowRSSIAPSteerEdge_root=20
CUOverloadTh_2G=95
CUOverloadTh_5G_L=85
CUOverloadTh_5G_H=85
MCSRateXingThreshold_DG=6000
MCSRateXingThreshold_UG=50000
RSSISteeringEdge_DG=21
RSSISteeringEdge_UG=29
RSSIRateXingThreshold_DG=21
RSSIRateXingThreshold_UG=29
MinRSSIOverload=20
ActivityThreshold=600000
MaxClientOverloaded=100
SteeringProhibitTime=10
BTMSteeringProhibitTime=30
SteeringUnfriendlyTime=10
BTMUnfriendlyTime=5
PHYBasedSelection=0
MinRssiIncTh_Root=5
MinRssiIncTh_RE=10
MinRssiIncTh_Peer=10
MetricReplntv=10
MetricPolicyChUtilThres_24G=0
MetricPolicyChUtilThres_5GH=0
ChPlanningChUtilThresh_24G=70
ChPlanningChUtilThresh_5GL=80
ChPlanningEDCCAThresh_24G=200
ChPlanningEDCCAThresh_5GL=200
ChPlanningOBSSThresh_24G=200
ChPlanningOBSSThresh_5GL=200
ChPlanningR2MonitorTimeoutSecs=300
ChPlanningR2MetricReportingInterval=10
ChPlanningR2MinScoreMargin=10
MetricPolicyRcpi_24G=0
MetricPolicyRcpi_5GL=0
MetricPolicyRcpi_5GH=0
