USHARE_NAME=CTSHARE
USHARE_IFACE=br0
USHARE_PORT=2468
USHARE_TELNET_PORT=
USHARE_DIR=/mnt/usb1_1
USHARE_OVERRIDE_ICONV_ERR=
USHARE_ENABLE_WEB=no
USHARE_ENABLE_TELNET=no
USHARE_ENABLE_XBOX=yes
USHARE_ENABLE_DLNA=
USHARE_TIME=
USHARE_FROM_CODE=
USHARE_TO_CODE=

