#注释行是#号开始，其他行是执行的命令

#mac table
brctl showmacs br0

#arp table
cat /proc/net/arp

#ipv6 neigh table
ip -6 neigh

#firewall
iptables -nvL  
iptables -nvL  -t nat
iptables -nvL  -t mangle
ip6tables -nvL
ip6tables -nvL  -t mangle

ip route
ip -6 route
ip rule show 
ip route show table 101
ip route show table 102
ip route show table 103
ip route show table 104
ip route show table 105
ip route show table 106
ip route show table 107
ip route show table 108
ip route show table 109
ip route show table 110
ip route show table 111
ip route show table 112

ifconfig


#查看编译时间
uname -a

#设备型号，设备能力
cat /ptrom/ptconf/device_info/*

#预配置镜像文件
ls -al /ptrom/preconfimg/

#sysinfo
cat /ptrom/ptconf/sysinfo_conf

#ps
ps

#查看分区，ubi信息，挂载信息
cat /proc/mtd
ubinfo -a
mount

#cpu
cat /proc/cpuinfo 

#内存
free
cat /proc/meminfo 

#flash
df

#boardid
cat /proc/nvram/boardid 

#启动命令行
cat /proc/cmdline 

#pon brcm
bs /b/e gpon
echo show ani gm > /dev/pondrv_dev;dmesg -c
echo show ani va >/dev/pondrv_dev;dmesg -c

#pon mtk
ponmgr gpon get info
ponmgr xgpon get info
ponmgr gpon get gemport
ponmgr gpon get tcont
gponmapcmd show
gponmapcmd showQueueRule


#qos
cat /var/qosCommand 
iptables -t mangle -nvL
ebtables -t broute -L --Lc
vlanctl --if veip0 --tx --tags 0 --show-table
vlanctl --if wan0 --tx --tags 0 --show-table
bs /b/e ip_class;dmesg -c
bs /b/e egress_tm;dmesg -c

#看加速表
#MTK
hw_nat -g;dmesg -c
#博通
cat /proc/fcache/*
archer flows;dmesg -c
bs /b/e ucast;dmesg -c


#runner
bs /b/nz;dmesg -c


#端口绑定
cat /proc/net/pt_br_port_info
cat /var/portbind_info 
ebtables -t broute -L

#ip route
ip rule show
ip -6 rule show
ip route show table 101
ip route show table 102
ip route show table 103
ip route show table 104
ip -6 route show table 501
ip -6 route show table 502
ip -6 route show table 503
ip -6 route show table 504

#光模块
i2c_cmd show optical

#catv
i2c_cmd show catv

#igmp
cat /proc/net/igmp_snooping
bs /b/e iptv;dmesg -c
bs /b/e mcast_wlan;dmesg -c
#MTK
brctl showsnoop br0;dmesg -c
cat /proc/tc3162/ecnt_multicast_hwnat_list


#报文统计
#ifconfig

