#注释行是#号开始
#首行以[]中带模块名开始，第二行是否执行的开关(yes或no)，第三行是日志触发条件，第四行是日志运行时间，第五行是日志关闭条件，第六行是开关控制的日志文件个数，第七行开始每行是开关控制的各日志的路径
#每个模块配置，各行之间不能有空白行或注释行

[hostapd]
run=no
touch /ptconf/hapd_dbg
60
rm /ptconf/hapd_dbg
3
/var/hostapd_wl0.log
/var/hostapd_wl1.log
/var/hostapd_wl2.log
