
#param.xml
/ptrom/ptconf/param_ct.xml
/ptrom/ptconf/param_ap.xml

#common
/var/servicemgr_modelog
/var/cfgcustz_modelog
/var/cfgmgr_modelog
/var/devfunc_modelog
/var/logmgr_modelog
/var/ptapi_modelog
/var/ptcfg_modelog
/var/sysmgr_modelog
/etc/passwd

#dhcpd
/var/udhcpd.log
/var/udhcpd_modelog
/ptconf/udhcpd.conf

#dnsmasq
/var/resolv*.conf
/ptconf/dnsmasq.conf

#lanmgr
/var/lanmgr_modelog

#telnet
/var/telnet.log

#tr069
/var/agent.log*

#wanmgr
/var/wanmgr_modelog
/var/wanconf/*

#radvd
/var/log/radvd.log
/var/appconf/radvd.conf

#dhcp6s
/var/appconf/dhcp6s.conf

#dhcpc
/var/udhcpc.log

#ftp
/ptconf/vsftpd.conf

#samba
/var/samba/smb.conf

#ddns
/var/inadyn_*.log

#upnp/pppoe/dhcp6c/dhcp6s
/ptconf/message_syslog


#硬件版本号，软件版本号
/ptrom/ptconf/sysinfo_conf

#产测及预配置
/ptdata/*

#升级
/var/upgrade_status_info
/var/upgrade_modelog
/var/kdrv_update_modelog

#syslog
/ptconf/message_syslog

#用户配置
/ptconf/usrconfig_conf

#led
/var/led_status
/var/led_light_record

#web
/var/web_modelog
/var/log/thttpd.log
/var/log/mini_httpd.log
/ptrom/ptconf/thttpd.conf
/ptrom/ptconf/mini_httpd.conf

#voice
/var/voice_modelog
/var/SipAppLog.txt

#event
/var/eventmgr_modelog

#ubus
/var/libptubus_modelog

#omci
/var/ptomci
/var/ptomci.bak
/var/ponhwal.log
/var/pondriver_modelog
/ptconf/xpon_tr069cfg_conf
/ptconf/xpon_voipcfg_conf

#netapi日志
/var/net_driver_modelog

#pstore
/ptconf/pstore/pstoreLog.tar.gz

