1
Connecting
NULL
IP_Routed
1_TR069_INTERNET_R_VID_100
0
0
NULL
NULL
0
1800
0
0
1
PPPoE
6420e17b0402@truehisp
password
NULL
NULL
NULL
0.0.0.0
0.0.0.0
1492
1492
1
0
0.0.0.0,0.0.0.0

0
PPPoE
NULL
NULL
AlwaysOn
NULL
0
0
0

0
NULL
TR069_INTERNET
100
0
0
0
1
0
-1
0
0
NULL
NULL
3
Connecting

NULL
AutoConfigured
,
1
NULL
PrefixDelegation
NULL
0
0

NULL
0
0
1400
1
