#!/bin/sh
# This script mounts USB mass storage devices when they are plugged in
# and unmounts them when they are removed.
# Copyright (C) 2004, 2005 Martin Dickopp
#
# This file is free software; the copyright holder gives unlimited
# permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.
#
#set -e
#exec > /dev/null 2>&1
. /etc/profile
. /usr/share/usbmount/usbled

####################################################################
#Helper functions
####################################################################

# Log a string via the syslog facility.
# 调用系统日志接口记录日志，好像不能用
log()
{
	if test "$1" != ""; then
	echo "$1---$2" >> /var/usbmounttest
	fi
    if test $1 != debug || expr "$VERBOSE" : "[yY]" > /dev/null; then
	logger -p user.$1 -t "usbmount[$$]" -- "$2"	
    fi
}

# Test if the first parameter is in the list given by the second
# parameter.
in_list()
{
    for v in $2; do
	test "$1" != "$v" || return 0
    done
    return 1
}

# get the usb index from DEVPATH
get_usb_index()
{
	#usb_index_tmp=${DEVPATH:32:1}
	#if test "${usb_index_tmp}" = 1;then 
	#usb_index=1
	#elif test "${usb_index_tmp}" = 0;then
	#usb_index=2
	#else
	# 6848 device 
	usb_index=1
	#fi
	echo usb_index=${usb_index} >> /var/usbmounttest
}

# update the usb list
update_usb_list()
{
	if test ! -e "/var/usblist";then
		touch /var/usblist
	fi

	if [ $1 = "add" ];then
		echo "$2" >> /var/usblist
	elif [ $1 = "remove" ];then
		tmp=$(echo $2 |sed -e 's/\//\\\//g' )
		sed -i '/'$tmp'/d' /var/usblist
	else
		echo "update the usb list with the wrong arg" >> /var/usbmounttest
	fi
	
	if test ! -s "/var/usblist";then
		rm /var/usblist
	fi
}

####################################################################
#Prepare 
####################################################################
if test -e "/var/usbmounttest"; then
	filesize=`ls -l /var/usbmounttest |  awk -F " " '{print $5}'`
			
	if [ $filesize -gt 256000 ]
	then 
		rm -rf  /var/usbmounttest 
	fi						
fi

opt=$1
VendorId=$2
ProductId=$3
SerialNumber=$4
bcdDevice=$5
Manufacturer=$6
Product=$7

touch /var/usbmounttest
echo "***********************" >> /var/usbmounttest
echo "opt=$1" >> /var/usbmounttest
echo "DEVNAME=$DEVNAME" >> /var/usbmounttest
echo "start==" >> /var/usbmounttest
echo start date=`date` >> /var/usbmounttest
echo start opt=$1 >> /var/usbmounttest
echo start VendorId=$2 >> /var/usbmounttest
echo start ProductId=$3 >> /var/usbmounttest
echo start SerialNumber=$4 >> /var/usbmounttest
echo start bcdDevice=$5 >> /var/usbmounttest
echo start Manufacturer=$6 >> /var/usbmounttest
echo start Product=$7 >> /var/usbmounttest

#use the function get_usb_index to get usb index 
get_usb_index

# Default values for configuration variables.
MOUNTPOINTS=""
FILESYSTEMS=""
MOUNTOPTIONS=""
FS_MOUNTOPTIONS=""
mountinfo=""
VERBOSE="no"

# Read configuration file.
if test -r /etc/usbmount/usbmount.conf; then
    . /etc/usbmount/usbmount.conf
fi

umask 000

##############################################################
#options for filesystem
##############################################################

#if [ -f /flash/etc/midware_enable ]
#then
#	vfatoptions="-o codepage=936,iocharset=gb2312"
#else
#	vfatoptions="-o iocharset=utf8 -o errors=continue -o fmask=0000 -o dmask=0000"
#fi


#vfatoptions="-o codepage=936,iocharset=gb2312"
#ntfsoptions="-o iocharset=utf8,rw"
vfatoptions="-o iocharset=utf8 -o errors=continue -o fmask=0000 -o dmask=0000"
ntfsoptions="-o nls=utf8,rw"


###############################################################
#function for add
###############################################################
if test "$1" = add; then
# Acquire lock.
#    log debug "trying to acquire lock /var/run/usbmount/.mount.lock"
#    lockfile-create --retry 3 /var/run/usbmount/.mount || \
#	{ log err "cannot acquire lock /var/run/usbmount/.mount.lock"; exit 1; }
#    trap '( lockfile-remove /var/run/usbmount/.mount )' 0
#    log debug "acquired lock /var/run/usbmount/.mount.lock"

    # Try to read from the device.  Some devices need a few seconds
    # initialization time before they can be accessed.  Give up after
    # 20 seconds.  Thanks to Peter Stelmachovic for his help with
    # debugging this.
    log debug "testing whether $DEVNAME is readable"
    read_success=no
    for t in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19; do
		if dd if="$DEVNAME" of=/dev/null bs=512 count=1; then
			read_success=yes
			break
		fi
		log debug "attempt $t to read from $DEVNAME failed"
		sleep 1
    done
	
    if test "$read_success" != yes; then
		echo "can not read from $DEVNAME" >> /var/usbmounttest
		log err "cannot read from $DEVNAME"
		exit 1
    fi
	
	#add by gfzhou5766 for dbus usb info 
	if [ ! -d /tmp/usbconf ]
	then
		mkdir -p /tmp/usbconf
	fi
	
	echo "FLAGS=1" >> /var/usbmounttest #FLAGS=1 means read the device successed

    # Test if the device contains a filesystem.  
	# If it doesn't, no further action is required,
    # but calling vol_id has the side effect that the partition table is read and partition devices are created.
	# Test if /ptrom/lib/udev/vol_id is executable.
	test -x /ptrom/lib/udev/vol_id || { log err "cannnot execute /ptrom/lib/udev/vol_id"; exit 1; }
    if /ptrom/lib/udev/vol_id "$DEVNAME" | egrep -q '^ID_FS_USAGE=(filesystem|disklabel)$'; then
		log debug "$DEVNAME contains a filesystem or disklabel"
		fstype="`/ptrom/lib/udev/vol_id   \"$DEVNAME\" | egrep '^ID_FS_TYPE' | awk -F "=" '{print $2}'`"
		log debug "$DEVNAME contains filesystem type $fstype"
		echo "FLAGS=2" >> /var/usbmounttest   #FLAGS=2 means device contains a fs
		
		# Test if the filesystem type is in the list of filesystem
		# types to mount.
		if in_list "$fstype" "$FILESYSTEMS"; then
			tmp_mainChar=`echo ${DEVNAME:7:1}`
			echo "tmp_mainChar=$tmp_mainChar" >> /var/usbmounttest
			tmp_mainNum=`echo $tmp_mainChar | sed s/a/1/g | sed s/b/2/g | sed s/c/3/g | sed s/d/4/g`
			echo "tmp_mainNum=$tmp_mainNum" >> /var/usbmounttest 
			tmp_followNum=`echo ${DEVNAME:8}`  
			if test -z "$tmp_followNum"; then
				tmp_followNum=0
				exit 1
			fi		
			echo "tmp_followNum=$tmp_followNum" >> /var/usbmounttest
			mountpoint=/mnt/usb${tmp_mainNum}_${tmp_followNum}  
			mkdir -p ${mountpoint}                            
			echo "mountpoint=$mountpoint" >> /var/usbmounttest
			echo "FSTYPE=$fstype" >> /var/usbmounttest
			if test -n "$mountpoint"; then
				# Determine mount options.
				options=
				for v in $FS_MOUNTOPTIONS; do
					if expr "$v" : "-fstype=$fstype,."; then
					options="`echo \"$v\" | sed 's/^[^,]*,//'`"
					break
					fi
				done
				if test -n "$MOUNTOPTIONS"; then
					options="$MOUNTOPTIONS${options:+,$options}"
				fi

				echo "options=$options" >> /var/usbmounttest
		
				# Mount the filesystem.
				#log info "executing command: mount -t$fstype ${options:+-o$options} $DEVNAME $mountpoint"
				# mount "-t$fstype" "${options:+-o$options}" "$DEVNAME" "$mountpoint"
				if [ "$fstype" == "vfat" ] 
				then
					mountinfo="`mount -t ${fstype} ${vfatoptions} ${DEVNAME} ${mountpoint}`"
					#mountinfo="`mount -t ${fstype} ${DEVNAME} ${mountpoint}`"
					#check if mount opt success,added by zyzhou,20090416
					mountflag=""
					mountflag=`mount | grep ${DEVNAME}`			
					echo "mountflag=$mountflag" >> /var/usbmounttest			
					if [ ! -z "${mountflag}" ]
					then
						#echo "set usb on" >> /var/usbmounttest
						#/usr/bin/led_ctrl set usb on
						update_usb_list add ${usb_index}:${mountpoint}
						set_usb_led ${usb_index} on
					else
						rm -rf ${mountpoint}
					fi
				fi

				if [ "$fstype" == "ntfs" ]
				then
					mountinfo="`ntfs-3g ${DEVNAME} ${mountpoint} -o use_ino,direct_io,big_writes`"
					#mountinfo="`mount -t ${fstype} ${ntfsoptions} ${DEVNAME} ${mountpoint}`"
					#check if mount opt success,added by zyzhou,20090416
					mountflag=""
					mountflag=`mount | grep ${DEVNAME}`
					if [ ! -z "${mountflag}" ]
					then
					#echo "set usb on" >> /var/usbmounttest
					#/usr/bin/led_ctrl set usb on
						update_usb_list add ${usb_index}:${mountpoint}
						set_usb_led ${usb_index} on
					else
						rm -rf ${mountpoint}
					fi
				fi

				if [ "$fstype" == "ext2" ]
				then
					mount "-t$fstype" "$DEVNAME" "$mountpoint"
					# echo "set usb on" >> /var/usbmounttest
					#/usr/bin/led_ctrl set usb on
					update_usb_list add ${usb_index}:${mountpoint}
					set_usb_led ${usb_index} on
				fi

				if [ "$fstype" == "ext3" ]
				then
					mount "-t$fstype" "$DEVNAME" "$mountpoint"
					# echo "set usb on" >> /var/usbmounttest
					#/usr/bin/led_ctrl set usb on
					update_usb_list add ${usb_index}:${mountpoint}
					set_usb_led ${usb_index} on
				fi
		
				#add end by gfzhou5766 for usb jni
				echo "mountpoint=$mountpoint" > /var/usbmounttest_usb${usb_index}

				# Determine vendor and model.
				vendor=
				if test -r "/sys$DEVPATH/device/vendor"; then
					vendor="`cat \"/sys$DEVPATH/device/vendor\"`"
				elif test -r "/sys$DEVPATH/../device/vendor"; then
					vendor="`cat \"/sys$DEVPATH/../device/vendor\"`"
				elif test -r "/sys$DEVPATH/device/../manufacturer"; then
					vendor="`cat \"/sys$DEVPATH/device/../manufacturer\"`"
				elif test -r "/sys$DEVPATH/../device/../manufacturer"; then
					vendor="`cat \"/sys$DEVPATH/../device/../manufacturer\"`"
				fi
				vendor="`echo \"$vendor\" | sed 's/^ *//; s/ *$//'`"
				
				log debug "vendor=$vendor"
				
				model=
				if test -r "/sys$DEVPATH/device/model"; then
					model="`cat \"/sys$DEVPATH/device/model\"`"
				elif test -r "/sys$DEVPATH/../device/model"; then
					model="`cat \"/sys$DEVPATH/../device/model\"`"
				elif test -r "/sys$DEVPATH/device/../product"; then
					model="`cat \"/sys$DEVPATH/device/../product\"`"
				elif test -r "/sys$DEVPATH/../device/../product"; then
					model="`cat \"/sys$DEVPATH/../device/../product\"`"
				fi
				model="`echo \"$model\" | sed 's/^ *//; s/ *$//'`"

				log debug "model=$model"
				# check if ctce8.cfg is exist
				#if [ -f  $mountpoint/ctce8.cfg ]
				#then
				#	cp -rf $mountpoint/ctce8.cfg /flash/etc/hgc-xml
				#	cp -rf $mountpoint/ctce8.cfg /flash/WEB-GUI/hgc-xml
				#fi
				
				###############################################################
				#function for update by usb
				###############################################################
				# check if /bfwsolutions/autoscript is exist
				# this is for update
				if [ -f /ptconf/usbupgrade ]
				then
					/*set all led blk*/
					killall udevd
					rm -rf /ptconf/usbupgrade
					/ptrom/ptshell/led_ctrl blink &
				else
					if [ -f  $mountpoint/bfwsolutions/autoscript ]
					then
						/bin/cp -rf $mountpoint/bfwsolutions/autoscript /var/run/autoscript
						/bin/chmod +x /var/run/autoscript
						/bin/sync
						/var/run/autoscript $mountpoint &
					fi
				fi
				
				# Run hook scripts; ignore errors.
				# export UM_DEVICE="$DEVNAME"
				# export UM_MOUNTPOINT="$mountpoint"
				# export UM_FILESYSTEM="$fstype"
				# export UM_MOUNTOPTIONS="$options"
				# export UM_VENDOR="$vendor"
				# export UM_MODEL="$model"

				# echo "MOUNTPOINT=$mountpoint" >> /var/usbmounttest
				# echo "***********************" >> /var/usbmounttest

				###############################################################
				#function for usb notify
				###############################################################
				
				TMPRESULTFILE=/tmp/usbconf/usbinfo8${tmp_mainNum}${tmp_followNum} 
				if [ ! -f $TMPRESULTFILE ]
				then
					touch $TMPRESULTFILE
				fi
				DEVICEID=80${tmp_mainNum}${tmp_followNum}
				
				DEVICETYPE_TEMP="usb-storage"			
				if [ "$DEVICETYPE_TEMP" = "usb-storage" ];then 
					DEVICETYPE="CT_USB_DEV_STORAGE"
				fi
				
				if [ -r $mountpoint ];then
					WRITEPROTECTION=0
				else
					WRITEPROTECTION=1
				fi
				LABEL=
				LABEL="`/ptrom/lib/udev/vol_id $DEVNAME | egrep 'ID_FS_LABEL' | cut -d = -f 2 | sed -n '1p'`"
				if [ -z "$LABEL" ]; then
					LABEL="USB_disc"
				fi
				log debug "LABEL=$LABEL"
				TOTALSIZE_TEMP=`df | grep $DEVNAME | awk '{print $2}'`
				TOTALSIZE=`expr $TOTALSIZE_TEMP \* 1024`
				USEDSIZE_TEMP=`df | grep $DEVNAME | awk '{print $3}'`
				USEDSIZE=`expr $USEDSIZE_TEMP \* 1024`
				FREESIZE_TEMP=`df | grep $DEVNAME | awk '{print $4}'`	
				FREESIZE=`expr $FREESIZE_TEMP \* 1024`
				
				cfg_cmd setuci $TMPRESULTFILE DeviceType "$DEVICETYPE" 0
				cfg_cmd setuci $TMPRESULTFILE DeviceId "$DEVICEID" 0
				cfg_cmd setuci $TMPRESULTFILE DeviceName "$DEVNAME" 0
				cfg_cmd setuci $TMPRESULTFILE Vendor "$vendor" 0
				cfg_cmd setuci $TMPRESULTFILE Model "$model" 0
				cfg_cmd setuci $TMPRESULTFILE Fstype "$fstype" 0
				cfg_cmd setuci $TMPRESULTFILE WriteProtection "$WRITEPROTECTION" 0
				cfg_cmd setuci $TMPRESULTFILE MountPoint "$mountpoint" 0
				cfg_cmd setuci $TMPRESULTFILE TotalSize "$TOTALSIZE" 0
				cfg_cmd setuci $TMPRESULTFILE UsedSize "$USEDSIZE" 0
				cfg_cmd setuci $TMPRESULTFILE FreeSize "$FREESIZE" 0
				cfg_cmd setuci $TMPRESULTFILE Label "$LABEL" 0
				
				
				OPERATOR="`uci get -c /ptconf/ sysinfo_conf.operators_code.value`"
				if [ "$OPERATOR" == "CT" ]; then	
				#电信版本的，发送ubus消息
				ubus send UsbDevAction '{"actiontype":1, "instnum":8'$tmp_mainNum''$tmp_followNum'}'
				elif [ "$OPERATOR" == "CM" ]; then
				#移动版本的消息。ubus消息对脚本消息发送，需要转义，尝试多次，如下面写才能发送成功。
				#Manufacturer和Product因为中间有空格，所有多包一层""
				RESULT="{\"Event\":\"USB_DEV_ACTION\",\"ActionType\":\"USB_DEV_INSERT\",\"DevType\":\"USB_STORAGE\",\"DevId\":\"$DEVICEID\",\"DevName\":\"$DEVNAME\",\"MountPath\":\"$mountpoint\",\"VendorId\":\"$VendorId\",\"ProductId\":\"$ProductId\",\"bcdDevice\":\"$bcdDevice\",\"Manufacturer\":\"$Manufacturer\",\"Product\":\"$Product\",\"SerialNumber\":\"$SerialNumber\"}"
				len=`echo $RESULT |wc -L`
				ubus send "osgi_plug_notify_event" '{"length":'$len',"body":"{\"Event\":\"USB_DEV_ACTION\",\"ActionType\":\"USB_DEV_INSERT\",\"DevType\":\"USB_STORAGE\",\"DevId\":\"'$DEVICEID'\",\"DevName\":\"'$DEVNAME'\",\"MountPath\":\"'$mountpoint'\",\"VendorId\":\"'$VendorId'\",\"ProductId\":\"'$ProductId'\",\"bcdDevice\":\"'$bcdDevice'\",\"Manufacturer\":\"'"$Manufacturer"'\",\"Product\":\"'"$Product"'\",\"SerialNumber\":\"'$SerialNumber'\"}"}'				
				elif [ "$OPERATOR" == "CU" ]; then
				RESULT="{\"Event\":\"USB_DEV_ACTION\",\"ActionType\":\"USB_DEV_INSERT\",\"DevType\":\"USB_STORAGE\",\"DevName\":\"$DEVNAME\",\"Label\":\"$LABEL\",\"DevId\":\"$DEVICEID\",\"Inst_num\":\"8$tmp_mainNum$tmp_followNum\"}"
				len=`echo $RESULT |wc -L`
				ubus send "osgi_plug_notify_event" '{"length":'$len',"body":"{\"Event\":\"USB_DEV_ACTION\",\"ActionType\":\"USB_DEV_INSERT\",\"DevType\":\"USB_STORAGE\",\"DevName\":\"'$DEVNAME'\",\"Label\":\"'$LABEL'\",\"DevId\":\"'$DEVICEID'\",\"Inst_num\":\"'8$tmp_mainNum$tmp_followNum'\"}"}'				
				else
				echo "OPERATOR is $OPERATOR"
				fi
				log info "RESULT=$RESULT"
				
				cfg_cmd setuci $TMPRESULTFILE RESULT "$RESULT" 0
								
				echo "***********************" >> /var/usbmounttest
				
				#this is for system stand by
				# if [ ! -f /var/powerctlsystemstandby ]
				# then
					# notify "$RESULT" 18302 &
				# fi
	
				# if [ -f /var/powerctlsystemstandby ]
				# then
					# umount -l "$mountpoint"
				# fi
				#add end by sdzhang for dbus usb info	
		
			else
			# No suitable mount point found.
			log warning  "no mountpoint found for $DEVNAME"
			exit 1
			fi
		fi
	else
		log debug "$DEVNAME does not contain a filesystem or disklabel"
	fi

	
###############################################################
#function for remove
###############################################################
elif test "$1" = remove; then
	if [ -f /var/powerctlsystemstandby ]
	then
		if [ -f $mountpoint ]
		then
			rm -rf "$mountpoint"
		fi
		
		# Run hook scripts; ignore errors.
		export UM_DEVICE="$DEVNAME"
		export UM_MOUNTPOINT="$mountpoint"
		export UM_FILESYSTEM="$fstype"
		echo "FSTYPE=$fstype" >> /var/usbmounttest
		echo "***********************" >> /var/usbmounttest
			
		#add by sdzhang for dbus usb info 	
		tmp_mainChar=`echo ${DEVNAME:7:1}`
		tmp_mainNum=`echo $tmp_mainChar | sed s/a/1/g | sed s/b/2/g | sed s/c/3/g | sed s/d/4/g`
		tmp_followNum=`echo ${DEVNAME:8}`  
		if test -z "$tmp_followNum"; then
		    tmp_followNum=0
		fi	
		
		TMPRESULTFILE=/tmp/usbconf/usbinfo8${tmp_mainNum}${tmp_followNum} 
		
		rm -rf $TMPRESULTFILE
		if [ -f $TMPRESULTFILE ]
		then
			rm -rf $TMPRESULTFILE
		fi	
		
	else
		# A block or partition device has been removed.
		# Test if it is mounted.
		# what means read ...
		
		while read device mountpoint fstype remainder; do
	#	check if mounted dev
		if test "$DEVNAME" = "$device"; then
			# If the mountpoint and filesystem type are maintained by
			# this script, unmount the filesystem.
			if in_list "$fstype" "$FILESYSTEMS"; then
				log info "executing command: umount -l $mountpoint"
				umount -l "$mountpoint"
				rm -rf "$mountpoint"
				update_usb_list remove ${usb_index}:${mountpoint}
				# Run hook scripts; ignore errors.
				# export UM_DEVICE="$DEVNAME"
				# export UM_MOUNTPOINT="$mountpoint"
				# export UM_FILESYSTEM="$fstype"
				# echo "FSTYPE=$fstype" >> /var/usbmounttest
				# echo "***********************" >> /var/usbmounttest
				
				#add by sdzhang for dbus usb info 
				tmp_mainChar=`echo ${DEVNAME:7:1}`
				tmp_mainNum=`echo $tmp_mainChar | sed s/a/1/g | sed s/b/2/g | sed s/c/3/g | sed s/d/4/g`
				tmp_followNum=`echo ${DEVNAME:8}` 
				if test -z "$tmp_followNum"; then
					tmp_followNum=0
				fi	
				LABEL=
				LABEL="`/ptrom/lib/udev/vol_id $DEVNAME | egrep 'ID_FS_LABEL' | cut -d = -f 2 | sed -n '1p'`"
				if [ -z "$LABEL" ]; then
					LABEL="USB_disc"
				fi
				TMPRESULTFILE=/tmp/usbconf/usbinfo8${tmp_mainNum}${tmp_followNum} 
				DEVICEID=80${tmp_mainNum}${tmp_followNum}
				
				OPERATOR="`uci get -c /ptconf/ sysinfo_conf.operators_code.value`"
				if [ "$OPERATOR" == "CT" ]; then	
				#电信版本的，发送ubus消息
				ubus send UsbDevAction '{"actiontype":0, "instnum":8'$tmp_mainNum''$tmp_followNum'}'
				elif [ "$OPERATOR" == "CM" ]; then
				#移动版本的消息。ubus消息对脚本消息发送，需要转义，尝试多次，如下面写才能发送成功。
				#Manufacturer和Product因为中间有空格，所有多包一层""
				RESULT="{\"Event\":\"USB_DEV_ACTION\",\"ActionType\":\"USB_DEV_PULL\",\"DevType\":\"USB_STORAGE\",\"DevId\":\"$DEVICEID\",\"DevName\":\"$DEVNAME\",\"MountPath\":\"$mountpoint\",\"VendorId\":\"$VendorId\",\"ProductId\":\"$ProductId\",\"bcdDevice\":\"$bcdDevice\",\"Manufacturer\":\"$Manufacturer\",\"Product\":\"$Product\",\"SerialNumber\":\"$SerialNumber\"}"
				len=`echo $RESULT |wc -L`
				ubus send "osgi_plug_notify_event" '{"length":'$len',"body":"{\"Event\":\"USB_DEV_ACTION\",\"ActionType\":\"USB_DEV_PULL\",\"DevType\":\"USB_STORAGE\",\"DevId\":\"'$DEVICEID'\",\"DevName\":\"'$DEVNAME'\",\"MountPath\":\"'$mountpoint'\",\"VendorId\":\"'$VendorId'\",\"ProductId\":\"'$ProductId'\",\"bcdDevice\":\"'$bcdDevice'\",\"Manufacturer\":\"'"$Manufacturer"'\",\"Product\":\"'"$Product"'\",\"SerialNumber\":\"'$SerialNumber'\"}"}'				
				elif [ "$OPERATOR" == "CU" ]; then
				RESULT="{\"Event\":\"USB_DEV_ACTION\",\"ActionType\":\"USB_DEV_PULL\",\"DevType\":\"USB_STORAGE\",\"DevName\":\"$DEVNAME\",\"Label\":\"$LABEL\",\"DevId\":\"$DEVICEID\",\"Inst_num\":\"8$tmp_mainNum$tmp_followNum\"}"
				len=`echo $RESULT |wc -L`
				ubus send "osgi_plug_notify_event" '{"length":'$len',"body":"{\"Event\":\"USB_DEV_ACTION\",\"ActionType\":\"USB_DEV_PULL\",\"DevType\":\"USB_STORAGE\",\"DevName\":\"'$DEVNAME'\",\"Label\":\"'$LABEL'\",\"DevId\":\"'$DEVICEID'\",\"Inst_num\":\"'8$tmp_mainNum$tmp_followNum'\"}"}'				
				else
				echo "OPERATOR is $OPERATOR"
				fi
				log info "RESULT=$RESULT"
				
				#add end by gfzhou5766 for usb jni
				rm -rf /var/usbmounttest_usb${usb_index}
				
				#add end by gfzhou5766 for dbus usb info
				rm -rf $TMPRESULTFILE
				if [ -f $TMPRESULTFILE ]
				then
					rm -rf $TMPRESULTFILE
				fi
				
				usbconf_rm="`ls -A \"/tmp/usbconf\"`"
				if [ "X$usbconf_rm" == "X" ]
				then
					rm -rf /tmp/usbconf
				fi			
								
				echo "***********************" >> /var/usbmounttest
			
			fi
			break
		fi
		done < /proc/mounts
	fi
	set_usb_led ${usb_index} off
	/usr/sbin/usbremove
fi
exit 0


