1
Connected
all
IP_Bridged
THSi
0
0
NULL
NULL
0
0
0
0
0
DHCP



0
0

1500

0

NULL
0
pon.293
0
dev.wla.7
INTERNET
293
0
0
0
-1
0
0
NULL
NULL
1
Unconfigured
NULL
NULL
AutoConfigured
NULL
1
NULL
PrefixDelegation
NULL
0
0
NULL
NULL
0
0
1400
1
