0
Unconfigured
NULL
NULL
NULL
0
0
NULL
NULL
0
1800
0
0
1
PPPOE
NULL
NULL
NULL
NULL
NULL
NULL
NULL
1492
1492
1
0
NULL
NULL
0
Disabled
NULL
NULL
AlwaysOn
NULL
0
0
0
NULL
0
NULL
NULL
0
0
0
0
1
0
-1
0
0
NULL
NULL
1
Unconfigured
NULL
NULL
AutoConfigured
NULL
1
NULL
PrefixDelegation
NULL
0
0
NULL
NULL
0
0
1400
1
